### ISSUE TITLE
Cannot compile with Ruby 3.3

### ISSUE THREAD

**Issue by Souravgoswami** [cybergizer-hq/LibmagicRb#1]
magic.c:43:26: error: initialization of ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(void **)’ [-Wincompatible-pointer-types]
   43 |                 .dfree = file_free,
      |                          ^~~~~~~~~
